# --- Database connection ---
flyway.url=jdbc:mysql://localhost:3306/kir_server_db
flyway.user=linemachine
flyway.password=1234fast

# --- Schema control ---
flyway.schemas=kir_server_db
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true

flyway.cleanDisabled=false

# --- Migration behavior ---
flyway.locations=filesystem:sql
